services:

  db:
    image: postgres:16
    container_name: postgres_cmsodeaanschiedam
    restart: "unless-stopped"
    shm_size: 128mb
    volumes:
      - pg_data_cmsodeaanschiedam:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cms_odeaanschiedam
      POSTGRES_USER: cms_odeaanschiedam
      POSTGRES_PASSWORD: "Connect2TheWorld!"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_cmsodeaanschiedam
    restart: "unless-stopped"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "steven_first@outlook.com"
      PGADMIN_DEFAULT_PASSWORD: "Connect2TheWorld!"
    volumes:
      - pgadmin_data_cmsodeaanschiedam:/var/lib/pgadmin
    depends_on:
      - db

  strapi:
    build: .
    container_name: strapi_cmsodeaanschiedam
    restart: unless-stopped
    volumes:
      - strapi_uploads_cmsodeaanschiedam:/usr/src/app/public/uploads
    ports:
      - "1337:1337"
    depends_on:
      - db
    environment:
      STRAPI_TELEMETRY_DISABLED: "true"
      SERVER_URL: http://localhost:1337
      HOST: 0.0.0.0
      PORT: 1337
      SMTP_HOST: smtp.hostinger.com
      SMTP_PORT: 465
      SMTP_USERNAME: "750@odeaanschiedam.nl"
      SMTP_PASSWORD: "@Connect2TheWorld"
      APP_KEYS: "NwAhp1aVqwmkUmHZo0xoAQ==,jJyib7TJi1sHQpwAteYSQg==,1UouFOEYsp7kgXOXyCNxSQ==,JwoDuYozYZ8eRkZY8H9fPQ=="
      API_TOKEN_SALT: "u2r21j6zV3i7wT+iK3Bn0Q=="
      ADMIN_JWT_SECRET: "fxTJ5nlz0GxVNUdQ+wwKQQ=="
      TRANSFER_TOKEN_SALT: "aDzc3IOMpz14RrgYINYGDw=="
      DATABASE_CLIENT: "postgres"
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: cms_odeaanschiedam
      DATABASE_USERNAME: cms_odeaanschiedam
      DATABASE_PASSWORD: "Connect2TheWorld!"
      DATABASE_SSL: "false"
      JWT_SECRET: "b/QdnEtNH4rnuK24KaAhgQ=="

volumes:
  strapi_uploads_cmsodeaanschiedam:
  pg_data_cmsodeaanschiedam:
  pgadmin_data_cmsodeaanschiedam:
