version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user1
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: cms_schiedam_750
    volumes:
      - wordpress:/var/www/html
      - ./schiedam-750-theme:/var/www/html/wp-content/themes/schiedam-750-theme

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: cms_schiedam_750
      MYSQL_USER: user1
      MYSQL_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
