name: Deploy Strapi CMS

on:
  push:
    paths:
      - 'cms-750-year-sdam/**'

jobs:
  deploy-cms:
    runs-on: ubuntu-latest

    steps:
    - name: Pull latest changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/ode-aan-schiedam
          git pull origin main

    - name: Setup environment file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/ode-aan-schiedam/cms-750-year-sdam
          echo "${{ secrets.ENV_FILE_CMS }}" > .env

    - name: Build application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/ode-aan-schiedam/cms-750-year-sdam
          yarn install
          yarn build

    - name: Deploy application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/ode-aan-schiedam/cms-750-year-sdam
          pm2 restart strapi