name: Deploy Strapi
on:
  push:
    branches:
      - main
    paths:
      - cms-750-year-sdam/**
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute deploy script
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ode-aan-schiedam
            git pull
            cd cms-750-year-sdam

            cat <<'EOF' > strapi.env
            ${{ secrets.STRAPI_ENV }}
            EOF

            cat <<'EOF' > postgres.env
            ${{ secrets.POSTGRES_ENV }}
            EOF

            cat <<'EOF' > pgadmin.env
            ${{ secrets.PGADMIN_ENV }}
            EOF
            
            docker compose up --build -d

            rm strapi.env
            rm postgres.env
            rm pgadmin.env
            
            echo "Done."
