name: Deploy NextJS
on:
  push:
    branches:
      - main
    paths:
      - next-750-year-sdam/**
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute deploy script
        uses: appleboy/ssh-action@v1
        env:
          ENV_FILE: ${{ secrets.NEXTJS_ENV }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: ENV_FILE
          script: |
            cd ode-aan-schiedam
            git pull
            cd next-750-year-sdam

            cat <<'EOF' > .env
            $ENV_FILE
            EOF
            
            docker compose up --build -d
            echo "Done."
